language: cpp

dist: xenial

env:
  global:
    - MAKEFLAGS="-j 2"

cache:
  directories:
    - /home/travis/build/PLD-H4111-COMP/Brutus/build/antlr4_runtime

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make
